version: '3.6'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test123!"
    ports:
      - "1433:1433"
  application:
    build: .
    environment:
      DBServer: "mssql"
    ports:
      - "8080:80"