// <auto-generated />
using ATOCalculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ATOCalculator.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210908032247_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ATOCalculator.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnualSalary")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SuperRate")
                        .HasColumnType("float");

                    b.Property<int>("paymentMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("ATOCalculator.Models.PaySlip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FromDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrossIncome")
                        .HasColumnType("int");

                    b.Property<int>("IncomeTax")
                        .HasColumnType("int");

                    b.Property<int>("NetIncome")
                        .HasColumnType("int");

                    b.Property<int>("Superannuation")
                        .HasColumnType("int");

                    b.Property<int>("TaxThresholdId")
                        .HasColumnType("int");

                    b.Property<string>("ToDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("payslip");
                });

            modelBuilder.Entity("ATOCalculator.Models.TaxThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("TaxRate1")
                        .HasColumnType("float");

                    b.Property<double>("TaxRate2")
                        .HasColumnType("float");

                    b.Property<double>("TaxRate3")
                        .HasColumnType("float");

                    b.Property<double>("TaxRate4")
                        .HasColumnType("float");

                    b.Property<double>("TaxRate5")
                        .HasColumnType("float");

                    b.Property<int>("Threshold1")
                        .HasColumnType("int");

                    b.Property<int>("Threshold2")
                        .HasColumnType("int");

                    b.Property<int>("Threshold3")
                        .HasColumnType("int");

                    b.Property<int>("Threshold4")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("taxThreshold");
                });
#pragma warning restore 612, 618
        }
    }
}
